apiVersion: v1
kind: Service
metadata:
  name: asyncrum-api-service
  namespace: asyncrum
spec:
  type: ClusterIP
  selector:
    app: asyncrum-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080